# Generated by Django 5.2.6 on 2025-09-16 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_provisionjob_batch_provisionjob_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provisionjob',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provisionjob',
            name='filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
