# Generated by Django 5.2.6 on 2025-09-16 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_provisionjob_date_provisionjob_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enactmentassignment',
            name='batch',
        ),
    ]
