# Generated by Django 5.2.6 on 2025-09-17 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_remove_enactmentassignment_batch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provisionjob',
            options={'ordering': ['id']},
        ),
    ]
