# Generated by Django 5.2.6 on 2025-09-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_provisionjob_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provisionjob',
            options={},
        ),
        migrations.AddField(
            model_name='provisionjob',
            name='document_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provisionjob',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provisionjob',
            name='review_outcome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
