# Generated by Django 5.2.6 on 2025-09-18 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_provisionjob_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provisionjob',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provisionjob',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
