# Generated by Django 5.2.6 on 2025-09-18 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_provisionjob_end_date_provisionjob_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='provisionjob',
            name='enactment_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobs.enactmentassignment'),
        ),
    ]
