# Generated by Django 5.2.6 on 2025-09-19 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_provisionjob_enactment_assignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enactmentassignment',
            name='is_reassigned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enactmentassignment',
            name='reassigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reassigned_assigments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enactmentassignment',
            name='reassigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned', to=settings.AUTH_USER_MODEL),
        ),
    ]
