# Generated by Django 5.2.6 on 2025-09-22 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_enactmentassignment_is_reassigned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provisionjob',
            name='generation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provisionjob',
            name='is_generated',
            field=models.BooleanField(default=False),
        ),
    ]
