# Generated by Django 5.2.6 on 2025-09-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_provisionjob_generation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provisionjob',
            name='document_rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
