# Generated by Django 5.2.6 on 2025-09-23 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_alter_provisionjob_document_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='provisionjob',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='provisionjob',
            name='date_assigned',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
