# Generated by Django 5.2.6 on 2025-09-23 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_provisionjob_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provisionjob',
            name='last_edited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
