# Generated by Django 5.2.6 on 2025-09-24 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_provisionjob_last_edited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provisionjob',
            name='document_rating',
            field=models.PositiveSmallIntegerField(blank=True, default=3, null=True),
        ),
    ]
