# Generated by Django 5.2.6 on 2025-09-24 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_alter_provisionjob_document_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provisionjob',
            name='review_outcome',
        ),
    ]
