# Generated by Django 5.2.6 on 2025-11-18 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_remove_provisionjob_review_outcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='provisionjob',
            name='enactment_identification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='provisionjob',
            name='enactment_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='provisionjob',
            name='have_am_or_not',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='provisionjob',
            name='provision_identification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
