# Generated by Django 5.2.6 on 2025-12-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_provisionjob_enactment_identification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provisionjob',
            name='in_qa',
            field=models.BooleanField(default=False),
        ),
    ]
