# Generated by Django 5.2.6 on 2025-12-19 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_provisionjob_in_qa'),
    ]

    operations = [
        migrations.AddField(
            model_name='provisionjob',
            name='is_rework',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='provisionjob',
            name='rework_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
