# Generated by Django 5.2.6 on 2025-09-16 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enactments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provision',
            name='batch',
        ),
    ]
