# Generated by Django 5.2.6 on 2025-09-16 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enactments', '0002_remove_provision_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='provision',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provisions', to='enactments.batch'),
        ),
    ]
