# Generated by Django 5.2.6 on 2025-09-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enactments', '0003_provision_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='enactment',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
