# Generated by Django 5.2.6 on 2025-09-19 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enactments', '0004_enactment_is_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enactment',
            name='is_done',
        ),
    ]
