# Generated by Django 5.2.6 on 2025-10-01 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enactments', '0005_remove_enactment_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
