# Generated by Django 5.2.6 on 2025-10-01 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_part_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='logged_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
