# Generated by Django 5.2.6 on 2025-12-03 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_logged_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='qa_priority',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
