# Generated by Django 5.2.6 on 2025-12-03 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_qa_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='qa_priority',
        ),
        migrations.AddField(
            model_name='user',
            name='qa_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
