# Generated by Django 5.2.6 on 2025-09-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_job_count', models.PositiveIntegerField(default=100)),
            ],
        ),
    ]
