# Generated by Django 5.2.6 on 2025-09-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsettings',
            name='qouta',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
