# Generated by Django 5.2.6 on 2025-09-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_jobsettings_qouta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobsettings',
            old_name='qouta',
            new_name='quota',
        ),
        migrations.AddField(
            model_name='jobsettings',
            name='parttime_quota',
            field=models.PositiveIntegerField(default=25),
        ),
    ]
