# Generated by Django 5.2.6 on 2025-12-01 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_rename_qouta_jobsettings_quota_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QASettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sampling_type', models.CharField(default='Normal', max_length=100)),
            ],
        ),
    ]
