# Generated by Django 5.2.6 on 2025-11-28 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('defects', '0005_alter_defectlog_screenshot'),
        ('jobs', '0016_provisionjob_enactment_identification_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QAMissingDefectLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('check_type', models.CharField(max_length=100)),
                ('remarks', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='QACluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('counter', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('qa_status', models.CharField(choices=[('completed', 'Completed'), ('ongoing', 'ONGOING'), ('pending', 'PENDING'), ('onhold', 'ONHOLD')], max_length=50)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QAClusterDisputes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('qa_cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qa.qacluster')),
            ],
        ),
        migrations.CreateModel(
            name='QADefectLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('incorrect', 'INCORRECT'), ('correct', 'CORRECT')], max_length=50)),
                ('dispute_reason', models.TextField()),
                ('remarks', models.TextField()),
                ('defect_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defects.defectlog')),
            ],
        ),
        migrations.CreateModel(
            name='QAJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_selected', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pass', 'PASS'), ('fail', 'FAIL')], max_length=50)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.provisionjob')),
                ('qa_cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qa.qacluster')),
                ('qa_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QASession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('qa_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='qa.qajob')),
            ],
        ),
    ]
