# Generated by Django 5.2.6 on 2025-11-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qacluster',
            name='manager_status',
            field=models.CharField(blank=True, choices=[('recompute', 'RECOMPUTE'), ('rework', 'REWORK'), ('complete', 'COMPLETE')], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='QAClusterDisputes',
        ),
    ]
