# Generated by Django 5.2.6 on 2025-12-03 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0004_usersamplingpriority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qajob',
            name='is_selected',
        ),
    ]
