# Generated by Django 5.2.6 on 2025-12-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0005_remove_qajob_is_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='qajob',
            name='outcome',
            field=models.CharField(blank=True, choices=[('pass', 'PASS'), ('fail', 'FAIL')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='qajob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('onhold', 'On Hold'), ('completed', 'Completed')], default='pending', max_length=50),
        ),
    ]
