# Generated by Django 5.2.6 on 2025-12-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0006_qajob_outcome_alter_qajob_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='qajob',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
