# Generated by Django 5.2.6 on 2025-12-03 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0008_alter_qajob_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qajob',
            name='qa_cluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_jobs', to='qa.qacluster'),
        ),
    ]
