# Generated by Django 5.2.6 on 2025-12-04 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0009_alter_qajob_qa_cluster'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QADefectLog',
        ),
    ]
