# Generated by Django 5.2.6 on 2025-12-04 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_provisionjob_in_qa'),
        ('qa', '0010_delete_qadefectlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qajob',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qa_job', to='jobs.provisionjob'),
        ),
    ]
