# Generated by Django 5.2.6 on 2025-12-05 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0011_alter_qajob_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='qamissingdefectlog',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qa.qajob'),
        ),
    ]
