# Generated by Django 5.2.6 on 2025-12-05 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0012_qamissingdefectlog_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qamissingdefectlog',
            old_name='job',
            new_name='qa_job',
        ),
    ]
