# Generated by Django 5.2.6 on 2025-12-09 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0013_rename_job_qamissingdefectlog_qa_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qajob',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('active', 'Active'), ('paused', 'Paused'), ('onhold', 'On Hold'), ('completed', 'Completed')], default='pending', max_length=50),
        ),
    ]
