# Generated by Django 5.2.6 on 2025-12-09 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0015_alter_qajob_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qajob',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('ongoing', 'Ongoing'), ('paused', 'Paused'), ('onhold', 'On Hold'), ('completed', 'Completed')], default='new', max_length=50),
        ),
    ]
