# Generated by Django 5.2.6 on 2025-12-09 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enactments', '0006_batch_start_date'),
        ('qa', '0016_alter_qajob_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='qacluster',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enactments.batch'),
        ),
    ]
