# Generated by Django 5.2.6 on 2025-12-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0017_qacluster_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='qacluster',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
