# Generated by Django 5.2.6 on 2025-12-11 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0018_qacluster_completed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qacluster',
            name='qa_status',
            field=models.CharField(blank=True, choices=[('completed', 'Completed'), ('ongoing', 'ONGOING'), ('pending', 'PENDING'), ('onhold', 'ONHOLD')], default='pending', max_length=50, null=True),
        ),
    ]
