# Generated by Django 5.2.6 on 2025-12-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0019_alter_qacluster_qa_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='qacluster',
            name='final_status',
            field=models.CharField(choices=[('pass', 'PASS'), ('fail', 'FAIL'), ('ongoing', 'ONGOING')], default='ongoing', max_length=50),
        ),
    ]
