# Generated by Django 5.2.6 on 2025-12-15 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0020_qacluster_final_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='qajob',
            name='job_error_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
