# Generated by Django 5.2.6 on 2025-12-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0021_qajob_job_error_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='qacluster',
            name='sample_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qacluster',
            name='sampling_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
