# Generated by Django 5.2.6 on 2025-12-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0022_qacluster_sample_size_qacluster_sampling_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qacluster',
            name='manager_status',
            field=models.CharField(blank=True, choices=[('recompute', 'RECOMPUTE'), ('rework', 'REWORK'), ('complete', 'COMPLETE'), ('pending', 'PENDING')], default='pending', max_length=50, null=True),
        ),
    ]
