# Generated by Django 5.2.6 on 2025-09-25 02:36

import django.db.models.deletion
import reports.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enactments', '0005_remove_enactment_is_done'),
        ('jobs', '0015_remove_provisionjob_review_outcome'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch_type', models.CharField(choices=[('full', 'Full Generation'), ('partial', 'Partial Generation')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=reports.models.report_file_upload_path)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_batches', to='enactments.batch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_batches', to=settings.AUTH_USER_MODEL)),
                ('jobs', models.ManyToManyField(related_name='report_batches', to='jobs.provisionjob')),
            ],
        ),
    ]
