# Generated by Django 5.2.6 on 2025-09-17 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0006_alter_provisionjob_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefectLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('completeness', 'Completeness'), ('structure', 'Structure'), ('chunking', 'Chunking'), ('hierarchy', 'Hierarchy'), ('local_styling', 'Local Styling'), ('complex_content', 'Complex Content'), ('version', 'Version')], max_length=50)),
                ('check_type', models.CharField(max_length=100)),
                ('severity_level', models.PositiveSmallIntegerField()),
                ('issue_description', models.TextField()),
                ('expected_outcome', models.CharField(max_length=255)),
                ('actual_outcome', models.CharField(max_length=255)),
                ('screenshot', models.ImageField(upload_to='defect_log_screenshots/')),
                ('link', models.URLField(blank=True, help_text='Option reference link', max_length=500, null=True)),
                ('error_count', models.PositiveIntegerField()),
                ('comments', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provision_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.provisionjob')),
            ],
        ),
    ]
