# Generated by Django 5.2.6 on 2025-09-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defectlog',
            name='id',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
