# Generated by Django 5.2.6 on 2025-09-22 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0003_defectcategory_defectoption'),
        ('jobs', '0010_provisionjob_generation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defectlog',
            name='provision_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defect_logs', to='jobs.provisionjob'),
        ),
    ]
