# Generated by Django 5.2.6 on 2025-09-23 12:45

import defects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0004_alter_defectlog_provision_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defectlog',
            name='screenshot',
            field=models.ImageField(upload_to=defects.models.defect_log_screenshot_path),
        ),
    ]
