# Generated by Django 5.2.6 on 2025-12-04 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0005_alter_defectlog_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='defectlog',
            name='dispute_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='defectlog',
            name='qa_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='defectlog',
            name='qa_status',
            field=models.CharField(blank=True, choices=[('incorrect', 'INCORRECT'), ('correct', 'CORRECT')], max_length=50, null=True),
        ),
    ]
