# Generated by Django 5.2.6 on 2025-12-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0006_defectlog_dispute_reason_defectlog_qa_remarks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defectlog',
            name='qa_status',
        ),
        migrations.AddField(
            model_name='defectlog',
            name='qa_correct',
            field=models.CharField(blank=True, choices=[('yes', 'YES'), ('no', 'NO')], max_length=50, null=True),
        ),
    ]
